language: python
python: "2.7"
script:
    - mkdir build
    - echo "artifact here" > build/here.log
branches:
    only:
      - master
deploy:
    - provider: s3
      access_key_id: $S3_KEY
      secret_access_key: $SECRET_KEY
      bucket: $BUCKET
      skip_cleanup: true
      local_dir: $TRAVIS_BUILD_DIR/build
      upload_dir: edx-analytics-dashboard
      acl: public_read
      on:
        branch: master
